services:
  - type: web
    name: City-Wide-DarkStore-Network
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app  # Use gunicorn for production
    autoDeploy: true
    region: oregon
